x-generator: NSwag v11.18.1.0 (NJsonSchema v9.10.66.0 (Newtonsoft.Json v11.0.0.0))
swagger: '2.0'
info:
  title: My Title
  version: 1.0.0
host: 'localhost:44364'
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /api/announcements:
    get:
      tags:
        - Announcement
      operationId: Announcement_GetAnnouncements
      parameters:
        - type: integer
          name: pageNumber
          in: query
          format: int32
          x-nullable: false
        - type: integer
          name: pageSize
          in: query
          format: int32
          x-nullable: false
        - type: string
          name: searchString
          in: query
          x-nullable: true
        - type: string
          name: fields
          in: query
          x-nullable: true
      responses:
        '200':
          x-nullable: true
          description: ''
          schema:
            type: file
    post:
      tags:
        - Announcement
      operationId: Announcement_CreateAnnouncement
      parameters:
        - name: announcement
          in: body
          required: true
          schema:
            $ref: '#/definitions/AnnouncementForCreation'
          x-nullable: true
      responses:
        '200':
          x-nullable: true
          description: ''
          schema:
            type: file
  '/api/announcements/{id}':
    get:
      tags:
        - Announcement
      operationId: Announcement_GetAnnouncement
      parameters:
        - type: string
          name: id
          in: path
          required: true
          format: guid
          x-nullable: false
        - type: string
          name: fields
          in: query
          required: true
          x-nullable: true
      responses:
        '200':
          x-nullable: true
          description: ''
          schema:
            type: file
    post:
      tags:
        - Announcement
      operationId: Announcement_BlockAnnouncementCreation
      parameters:
        - type: string
          name: id
          in: path
          required: true
          format: guid
          x-nullable: false
      responses:
        '200':
          x-nullable: true
          description: ''
          schema:
            type: file
    patch:
      tags:
        - Announcement
      operationId: Announcement_PatchAnnouncement
      parameters:
        - type: string
          name: id
          in: path
          required: true
          format: guid
          x-nullable: false
        - name: patchDoc
          in: body
          required: true
          schema:
            $ref: '#/definitions/JsonPatchDocumentOfAnnouncementForUpdate'
          x-nullable: true
      responses:
        '200':
          x-nullable: true
          description: ''
          schema:
            type: file
    put:
      tags:
        - Announcement
      operationId: Announcement_PutAnnouncement
      parameters:
        - type: string
          name: id
          in: path
          required: true
          format: guid
          x-nullable: false
        - name: announcement
          in: body
          required: true
          schema:
            $ref: '#/definitions/AnnouncementForUpdate'
          x-nullable: true
      responses:
        '200':
          x-nullable: true
          description: ''
          schema:
            type: file
    delete:
      tags:
        - Announcement
      operationId: Announcement_DeleteAnnouncement
      parameters:
        - type: string
          name: id
          in: path
          required: true
          format: guid
          x-nullable: false
      responses:
        '200':
          x-nullable: true
          description: ''
          schema:
            type: file
definitions:
  AnnouncementForCreation:
    type: object
    additionalProperties: false
    allOf:
      - $ref: '#/definitions/AnnouncementManipulation'
  AnnouncementManipulation:
    type: object
    x-abstract: true
    additionalProperties: false
    required:
      - title
      - description
      - phone
      - vipAnnouncement
    properties:
      title:
        type: string
        maxLength: 100
        minLength: 1
      description:
        type: string
        maxLength: 250
        minLength: 1
      phone:
        type: string
        maxLength: 20
        minLength: 1
        pattern: '^(1-)?\(\d{3}\)-\d{3}-\d{3}$'
      imageName:
        type: string
      vipAnnouncement:
        type: boolean
  JsonPatchDocumentOfAnnouncementForUpdate:
    type: object
    additionalProperties: false
    properties:
      operations:
        type: array
        items:
          $ref: '#/definitions/OperationOfAnnouncementForUpdate'
  OperationOfAnnouncementForUpdate:
    type: object
    additionalProperties: false
    allOf:
      - $ref: '#/definitions/Operation'
  Operation:
    type: object
    additionalProperties: false
    properties:
      value: {}
    allOf:
      - $ref: '#/definitions/OperationBase'
  OperationBase:
    type: object
    additionalProperties: false
    properties:
      path:
        type: string
      op:
        type: string
      from:
        type: string
  AnnouncementForUpdate:
    type: object
    additionalProperties: false
    allOf:
      - $ref: '#/definitions/AnnouncementManipulation'
